proposals/proposal_2020_12_rate-limiting.md
This PR is a proposal for rate limiting builds. This PR is meant to be the place to discuss the options I laid out or anything I missed :) 
If interested in some of the research I did in the other CI tools - you can see it [here](https://github.com/go-vela/community/issues/161)
If I had to put forth a recommendation I'd say the `Option MVP` one as it seems feasible to ship with v0.7.0 and solves the problems laid out in the problem statement. Once done it would be easier to modify the different parts to look more like `option A` (or make changes to that based on user feedback... something like don't build a car when all we needed was a skateboard).
=> Rate limiting builds proposal

migrations/v0.7.0/main.go
A couple improvements being made here:
* added code comments for clarity
* added more log messages using `github.com/sirupsen/logrus`
* enabled setting the log level for logrus via `VELA_LOG_LEVEL` environment variable
* created an `output` string that is set based off the secret type:
* `repo`: `repo/<org>/<repo>/<name>`
* `org`: `org/<org>/*/<name>`
* `shared`: `shared/<org>/<team>/<name>`
=> chore(v0.7.0): add more logging and code comments

releases/v0.6.1.md, releases/v0.6.2.md
Adding the release notes for the `v0.6.x` patches
=> chore(releases): add v0.6.x patch release notes

migrations/v0.7/go.mod, migrations/v0.7/go.sum
`go get -u ./...`
`make clean`
=> chore: update dependencies

releases/v0.7.3.md, releases/v0.7.4.md
Adding the release notes for the `v0.7.x` patches
=> chore(releases): add v0.7.x patch release notes

migrations/v0.8/README.md
This adds the required environment variable changes between `v0.7.x` and `v0.8.x` for Vela.
For the [go-vela/server](https://github.com/go-vela/server):
* https://github.com/go-vela/server/pull/331
* https://github.com/go-vela/server/pull/333
* https://github.com/go-vela/server/pull/336
* https://github.com/go-vela/server/pull/418
For the [go-vela/worker](https://github.com/go-vela/worker):
* https://github.com/go-vela/worker/pull/178
* https://github.com/go-vela/worker/pull/181
* https://github.com/go-vela/pkg-runtime/pull/110
=> enhance(migrations/v0.8): update environment variable configuration

migrations/v0.8/README.md, releases/v0.8.1.md
This adds the release notes for the `v0.8.1` release
=> chore(releases): add v0.8.1 release notes

releases/v0.8.0.md
Addressing feedback from https://github.com/go-vela/community/pull/276#issuecomment-853360888
cc: @JordanSussman
=> enhance(releases): add links for v0.8.0 release notes

proposals/2021/README.md, proposals/2022/README.md, proposals/README.md
- add 2022 folder
- add reference to template in proposal readme
=> chore: proposal folder fix

releases/v0.12.md, releases/v0.13.md
adds some missing info on minor version bumps/releases
=> chore: add minor version bump info

releases/v0.14.md
also added API permission change introduced in 0.14.x to breaking change notice
=> chore(v0.14.x): update with bug fix releases

migrations/README.md
Was planning my v0.14 migration and found that these links were a little off :^)
=> chore: Correct Migrations README Links

proposals/2023/03-15_worker-auth.md
=> chore(proposal): add implementation PR links to worker auth proposal

releases/v0.18.md
add missed changed flag under breaking change for admins
=> fix(releases/0.18): add changed flag names

.gitignore, releases/scripts/relgen.sh, releases/v0.19.md
script is kinda wip for now, but should be helpful at this point even. currently assumes a new full release tag has been cut on each repo.
will wait for some of the doc PRs to get merged to cross reference.
=> chore: v0.19 relnotes

migrations/README.md, releases/README.md, releases/v0.21.md
note: depends on https://github.com/go-vela/community/pull/857
=> chore(v0.21): add release notes

releases/v0.22.md
Shameless self promotion incoming
Looks like the relgen script did not like dashes
=> fix(v22_release_notes): add references to auto-cancel

releases/scripts/relgen.sh
for some reason "-", when used in scope, wasn't being captured. and the fix is to move it to be the last character in the list to look for?! :shrug:
=> fix(releases/script): make sure to capture dash in scope

proposals/2024/03-07_platform-settings.md, proposals/2024/README.md, proposals/README.md
=> feat(proposal): dynamic platform settings

releases/v0.26.md
markdown formatter had a word too. seems to render fine 🤷🏼‍♂️
=> chore(release notes): add v0.26.4 info

.github/README.md
while the previously linked-to site does talk about zero versioning, it is a bit tongue-in-cheek. let's just reference semver official spec.
=> enhance: versioning info
