go-vela/community

- LICENSE
- migrations/v0.7.0/Dockerfile
- migrations/v0.7.0/Makefile
- migrations/v0.7.0/main.go
This is a general housekeeping task.
I used VS code's search and replace:
* Search: `Copyright (c) 2020`
* Replace: `Copyright (c) 2021`
At the top of every file, the new copyright statement now looks like:
```
// Copyright (c) 2021 Target Brands, Inc. All rights reserved.
```
> chore: update copyright year to 2021

- migrations/v0.7/database.go
- migrations/v0.7/go.mod
- migrations/v0.7/go.sum
- migrations/v0.7/run.go
This adds an `Exec()` function to the `go-vela/community/migrations/v0.7/db` type 👍 
This function will perform the following:
* [Capture a list of all builds](https://github.com/go-vela/server/blob/master/database/build.go#L106-L131) from the database
* Iterate through that list of builds
* [Capture a list of logs for the build](https://github.com/go-vela/server/blob/master/database/log.go#L17-L56) from the database
* Iterate through that list of logs
* [Update log entry](https://github.com/go-vela/server/blob/master/database/log.go#L157-L183) with compression
This utility directly uses the `go-vela/server/database` package, so [we get the compression by calling `UpdateLog()`](https://github.com/go-vela/server/blob/9a01b0a0d9bc38302792237bb457fec6fb51b06f/database/log.go#L170-L176): …
> feat(migrations): add database exec function

- migrations/v0.7/DOCS.md
- migrations/v0.7/Dockerfile
- migrations/v0.7/Makefile
* Updated the `Makefile` to build Golang binaries for multiple operating systems and architectures
* Updated the `Dockerfile` to account for this
* Added a `DOCS.md` file containing information on how to setup and run the migration utility
> chore: cleanup Makefile and migration documentation

- migrations/v0.7/database.go
Currently, if you run the utility against the database you'll find output like this:
```sh
$ release/darwin/amd64/vela-migration \
--database.driver postgres \
--database.config '<config string from server>'
{"level":"info","msg":"capturing all builds from the database","time":"2021-02-22T13:28:05-06:00"}
{"level":"info","msg":"capturing all logs for build 1","time":"2021-02-22T13:28:05-06:00"}
{"level":"error","msg":"unable to decompress logs for build 1: zlib: invalid header","time":"2021-02-22T13:28:05-06:00"}
{"level":"error","msg":"unable to decompress logs for build 1: zlib: invalid header","time":"2021-02-22T13:28:05-06:00"}
{"level":"error","msg":"unable to decompress logs for build 1: zlib: invalid header","time":"2021-02-22T13:28:05-06:00"}
{"level":"info","msg":"all logs …
```
> enhance(v0.7): ignore expected decompress logs from database client

- migrations/v0.7/README.md
Related to https://github.com/go-vela/server/pull/301
This updates the documentation to reflect the unused indexes we can drop.
Here is a list of all indexes that would be removed:
* `builds_repo_id_number`
* `hooks_repo_id_number`
* `logs_step_id`
* `logs_service_id`
* `repos_full_name`
* `secrets_type`
* `services_build_id_number`
* `steps_build_id_number`
* `users_name`
> docs(v0.7): add unused indexes to drop

- migrations/v0.7/alter.go
- migrations/v0.7/compress.go
- migrations/v0.7/database.go
- migrations/v0.7/go.mod
- migrations/v0.7/run.go
This adds logic to execute the `ALTER` statements documented in the `README.md` for this utility.
https://github.com/go-vela/community/blob/master/migrations/v0.7/README.md
The following `ALTER` statements would be executed:
* `ALTER TABLE builds ADD COLUMN IF NOT EXISTS deploy_payload VARCHAR(2000);`
* `ALTER TABLE users ADD COLUMN IF NOT EXISTS refresh_token VARCHAR(500);`
* `ALTER TABLE workers ADD COLUMN IF NOT EXISTS build_limit INTEGER;`
> enhance(v0.7): add logic to perform table alterations

- migrations/v0.7/compress.go
- migrations/v0.7/database.go
- migrations/v0.7/go.mod
- migrations/v0.7/go.sum
- migrations/v0.7/main.go
- migrations/v0.7/run.go
We ran the currently utility against our lower environment to get a feel for how long things might take for production.
Unfortunately, it took ~ `2` hours to compress logs for ~ `35k` builds.
This enables the utility to concurrently compress build logs stored in the database.
This can be set via the flag `concurrency.limit` or environment variables:
* `VELA_CONCURRENCY_LIMIT`
* `CONCURRENCY_LIMIT`
The default concurrency limit is set to `4` to help speed things up while being mindful of the underlying system.
This also has an added benefit of being able to "turn off" concurrency by passing a limit of `1`.
> feat(v0.7): concurrently compress build logs

- migrations/v0.7/DOCS.md
- migrations/v0.7/Makefile
- migrations/v0.7/compress.go
- migrations/v0.7/database.go
- migrations/v0.7/main.go
- migrations/v0.7/run.go
This enables the utility to skip compressing logs for certain builds that meet the defined criteria in the database.
The first set of criteria is specifically looking at the `status` field for a build.
If a build is in a `pending` or `running` status, we can reasonably assume the build is going to run or is running.
We don't want to corrupt the logs data for builds in those states so we ignore compressing the logs for them.
The second set of criteria is specifically looking at the `id` field for a build.
When upgrading to the latest release, you'll have log data stored in the database in a compressed state.
In order to help improve efficiency, we've added a variable that you can configure to ignore builds with a specific `id`.
This can be set via the flag `build.limit` or environment …
> feat(v0.7): skip builds meeting certain criteria

- .github/README.md
I found that the links are broken on `README` because the path specified were wrong. Corrected.
> Fix readme's broken link to documents

- migrations/v0.7/compress.go
- migrations/v0.7/database.go
- migrations/v0.7/encrypt.go
- migrations/v0.7/go.mod
- migrations/v0.7/go.sum
- migrations/v0.7/main.go
- migrations/v0.7/run.go
Dependent on https://github.com/go-vela/server/pull/304
When upgrading to the latest release, you'll have secret values stored in the database in an encrypted state.
This enables the utility to concurrently encrypt secret values stored in the database.
This can be set via the existing flag `concurrency.limit` or environment variables:
* `VELA_CONCURRENCY_LIMIT`
* `CONCURRENCY_LIMIT`
The default concurrency limit is still set to `4`.
This also has an added benefit of being able to "turn off" concurrency by passing a limit of `1`.
Also, in order to help improve efficiency, we've added a variable that you can configure to ignore secrets with a specific `id`.
This can be set via the flag `secret.limit` or environment variables:
* `VELA_SECRET_LIMIT`
* `SECRET_LIMIT`
The default secret limit …
> feat(v0.7): add logic to concurrently encrypt secrets

- migrations/v0.7/DOCS.md
- migrations/v0.7/Makefile
- migrations/v0.7/database.go
- migrations/v0.7/exec.go
- migrations/v0.7/main.go
- migrations/v0.7/run.go
- migrations/v0.7/validate.go
This enables the migration utility to invoke specific operations when trying to migrate to a `v0.7.x` release.
The following actions can be provided via their flag names:
* `all` - run all supported actions configured in the migration utility
* `alter.tables` - runs the action responsible for altering database tables
* `compress.logs` - runs the action responsible for compressing all logs
* `drop.indexes` - runs the action responsible for dropping unused indexes
* `encrypt.secrets` - runs the action responsible for encrypting secret values
Each of these actions can also be provided via environment variables:
* `VELA_ALL`
* `VELA_ALTER_TABLES` or `ALTER_TABLES`
* `VELA_COMPRESS_LOGS` or `COMPRESS_LOGS`
* `VELA_DROP_INDEXES` or `DROP_INDEXES`
* `VELA_ENCRYPT_SECRETS` or `ENCRYPT_SECRETS`
> feat(v0.7): add action flags to invoke specific operations

- migrations/v0.7/README.md
Here's an example of what the `README.md` looks like now:
https://github.com/go-vela/community/blob/docs/migrations/v0.7/readme/migrations/v0.7/README.md
> docs(v0.7): update README for v0.7 migration utility

- migrations/v0.8/DOCS.md
- migrations/v0.8/Makefile
- migrations/v0.8/README.md
- migrations/v0.8/database.go
- migrations/v0.8/encrypt.go
- migrations/v0.8/exec.go
- migrations/v0.8/main.go
- migrations/v0.8/run.go
- migrations/v0.8/validate.go
Related to https://github.com/go-vela/server/pull/320
When upgrading to the latest release (`v0.8.x`), you'll have user fields stored in the database in an encrypted state.
To accomplish this, you'll be required to provide the encryption key to the utility.
This can be set via the existing flag `database.encryption.key` or environment variables:
* `VELA_DATABASE_ENCRYPTION_KEY`
* `DATABASE_ENCRYPTION_KEY`
This also enables the utility to concurrently encrypt user fields that are already stored in the database.
This can be set via the existing flag `concurrency.limit` or environment variables:
* `VELA_CONCURRENCY_LIMIT`
* `CONCURRENCY_LIMIT`
The default concurrency limit is still set to `4`.
This also has an added benefit of being able to "turn off" concurrency by passing a limit of `1`.
> feat(v0.8): add logic to concurrently encrypt users

- releases/v0.8.0.md
This adds the release notes for the `v0.8.0` release
> chore(releases): add v0.8.0 release notes

- .github/renovate.json
tweaking renovate bot with the goal of preventing PRs for `github.com/go-vela` dependencies.
in this repo, those dependencies are typically purposefully pinned at certain versions for compatibility.
> chore: tweak renovate config

- proposals/2020-05-22_external-secrets.md
- proposals/README.md
This adds the proposal information for the external `secrets` feature in Vela.
> feat(proposals): add external secrets information

- proposals/2020-06-01_pull-policy.md
- proposals/README.md
This adds the proposal information for the `pull` policies feature in Vela.
> feat(proposals): add pull policies information

- proposals/2020-06-09_default-secrets.md
- proposals/README.md
This adds the proposal information for the default secret `engine` in Vela.
> feat(proposals): add default secrets information

- .github/PULL_REQUEST_TEMPLATE/proposal.md
- proposals/2020/04-16_deployments.md
- proposals/2020/05-22_external-secrets.md
- proposals/2020/06-01_pull-policy.md
- proposals/2020/06-09_default-secrets.md
- proposals/2020/12-16_rate-limiting.md
- proposals/2020/README.md
- proposals/README.md
This condenses all `2020-*` markdown files into a single directory under `proposals`.
> refactor(proposals): condense 2020 proposals into directory

- proposals/2019/07-01_templates.md
- proposals/2019/README.md
- proposals/README.md
This adds the proposal information for the `templates` feature in Vela.
> feat(proposals/2019): add templates information

- releases/v0.8.md
This adds the release notes for the `v0.8.3` and `v0.8.4` releases:
* [go-vela/server@v0.8.3](https://github.com/go-vela/server/releases/tag/v0.8.3)
* [go-vela/server@v0.8.4](https://github.com/go-vela/server/releases/tag/v0.8.4)
> chore(releases/v0.8): add v0.8.3 and v0.8.4 release notes

- proposals/2019/07-16_secrets.md
- proposals/2019/README.md
- proposals/README.md
This adds the proposal information for the `secrets` feature in Vela.
> feat(proposals/2019): add secrets information

- proposals/2019/08-13_concurrency.md
- proposals/2019/08-13_stages.md
- proposals/2019/README.md
- proposals/README.md
This adds the proposal information for the `stages` feature in Vela.
> feat(proposals/2019): add stages information

- proposals/2019/11-05_routing.md
- proposals/2019/README.md
- proposals/README.md
This adds the proposal information for routing `builds` to the queue.
> feat(proposals/2019): add build routing information

- proposals/2021/07-22_log-streaming.md
- proposals/2021/README.md
- proposals/README.md
Part of the effort for https://github.com/go-vela/community/issues/156
Closes https://github.com/go-vela/community/issues/349
This adds the proposal information for streaming `logs` for `steps` and `services` (all contained in a `build`).
In this proposal, are three different approaches to streaming logs for a step/service in Vela:
* [Option 1](../blob/feature/proposals/2021/log_streaming/proposals/2021/07-22_log-streaming.md#option-1)
Simulates streaming logs from the [go-vela/worker](https://github.com/go-vela/worker) to the [go-vela/server](https://github.com/go-vela/server) by uploading them on a regular time interval
* [Option 2](../blob/feature/proposals/2021/log_streaming/proposals/2021/07-22_log-streaming.md#option-2)
Streams logs from the …
> feat(proposals/2021): add log streaming information

- proposals/2021/07-22_log-streaming.md
- proposals/2021/08-25_repo-structure.md
- proposals/2021/README.md
- proposals/README.md
This proposes to condense the current repo structure in the [go-vela](https://github.com/go-vela) org.
Currently, we have `11` "core" repos for Vela.
After this proposal, we'd be left with `6` "core" repos for Vela.
> NOTE:
>
> In this context, a "core" repo is any repos that require code or dependency changes in order to release the product.
The intention of this proposal is to accomplish the following:
* condense and simplify the "core" repo structure
* improve consistency among the "core" repos
* ease the burden necessary to contribute functionality to the product
* reduce the level of overhead when attempting to publish new releases
The final structure for the "core" repos would look like:
```diff
1. cli
- compiler: moved -> server
- mock: moved -> server/worker
- pkg-executor: moved …
```
> feat(proposals/2021): add information for repo structure

- releases/v0.12.md
releases between server, worker and cli diverged a little so the notes had be a little more messy but also more accurate :)
> chore: fix notes for v0.12.x releases

- releases/v0.13.md
the feature that is being removed from the release notes was reverted in https://github.com/go-vela/types/pull/241 which is part of v0.13.x release.
> fix(v0.13.x): remove reverted feature

- releases/v0.13.md
This updates the breaking change for secrets in the `v0.13` release notes.
Specifically, it adds a syntax example and links to the existing syntax examples in our docs.
> fix(releases/v0.13): show secrets syntax for breaking change

- .github/renovate.json
see https://docs.renovatebot.com/configuration-options/#excludepackagepatterns
we had a few PRs comes through that we had to manually close. this rule should have prevented that, but it looks like the configuration option has changed? or maybe it was always wrong.
as a reminder, this rule exists to prevent automatic updates for go-vela specific packages related to the migrations folder. those have to be pinned to specific vela versions for them to work.
> fix(renovate): adjust config to exclude packages

- proposals/2023/02-23_build-tokens.md
- proposals/2023/README.md
Ref:
- https://github.com/go-vela/server/pull/765
- https://github.com/go-vela/sdk-go/pull/201
- https://github.com/go-vela/worker/pull/427
- https://github.com/go-vela/types/pull/276
> feat(auth): build token proposal

- releases/v0.19.md
this one got missed due not following conventional commit pattern.
> fix(0.19): add missing contribution

- .github/renovate.json
this change should reduce PR noise here a bit on the /migrations folder via:
- limit github.com/go-vela/* modules to patch only; in /migrations, those are pinned intentionally and shouldn't be upgraded by minor/major version
- we use "latest" for dockerfile, pinning to digest is just noise; ignore dockerfiles
> fix(renovate): go-vela modules patch only, ignore dockerfiles

- migrations/README.md
- migrations/v0.22/README.md
- releases/README.md
- releases/scripts/relgen.sh
- releases/v0.22.md
- add v0.22 release notes
- small tweak to release script to account for commits with slashes in scope (for example, `fix(something/big): adjust hat radius`)
markdown linter/formatter apparently had its way a little bit here.
> chore(release/v0.22): add v0.22 release notes

- migrations/v0.23/README.md
- migrations/v0.23/scripts/migration-postgres.sql
- migrations/v0.23/scripts/migration-sqlite.sql
- releases/v0.23.md
remove commits that belonged to v0.23.1 from new v0.23.2 section. call out other CVEs being addressed. update migration script to account for new column in secrets table.
> chore(release-notes): tweaks to v0.23.2 release notes

- migrations/v0.23/README.md
This change resolves an issue when attempting to run the recommended SQL queries for the `v0.23` migration:
https://github.com/go-vela/community/tree/main/migrations/v0.23#recommended
The fix is to update the first recommended SQL query from:
```sql
UPDATE secrets SET allow_commands = false WHERE type = 'shared';
```
to:
```sql
UPDATE secrets SET allow_command = false WHERE type = 'shared';
```
When attempting to follow the docs in their current state, I was met with this output from Postgres:
```sql
vela=> UPDATE secrets SET allow_commands = false WHERE type = 'shared';
ERROR:  column "allow_commands" of relation "secrets" does not exist
LINE 1: UPDATE secrets SET allow_commands = false WHERE type = 'shar...
```
> fix(migrations/v0.23): allow_commands -> allow_command

- proposals/2022/07-01_nested_api_objects.md
Co-authored-by: @ecrupper
Please vote for which option you prefer the most:
* [Option 1](https://github.com/go-vela/community/blob/feature/proposal/nested_api_objects/proposals/2022/07-01_nested_api_objects.md#option-1)
* [Option 2](https://github.com/go-vela/community/blob/feature/proposal/nested_api_objects/proposals/2022/07-01_nested_api_objects.md#option-2)
> feat(proposals): add nested API objects

- proposals/2024/12-27_dynamic-ruleset.md
- proposals/README.md
Adding a new proposal to allow dynamic ruleset without needing to invoke templates.
> feat: add new proposal for dynamic ruleset
